name: dashboard
description: Dashboard for visualising messages and themes
# version: 1.0.0

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  firebase: ^7.2.1
  chartjs:
    git: git@github.com:marianamarasoiu/chartjs.dart.git
  mapbox_gl_dart: ^0.1.4

dev_dependencies:
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
